name: Man10Dicelottery
version: '${project.version}'
main: yusama125718_209282ihcuobust.man10dicelottery.Man10Dicelottery
api-version: 1.17

commands:
  mlot:
    description: start lottery
    usage: /<command> [text] [text]

parmissions:
  mdicelottery.op:
    default: op
  mdicelottery.player:
    default: true
